# Support Vector Machine (SVM)

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('ids.csv')
dataset.drop("Timestamp",axis=1,inplace=True)
dataset["Flow Pkts/s"]=pd.to_numeric(dataset["Flow Pkts/s"],errors="coerce")
dataset.dropna(inplace=True)
dataset.replace([np.inf, -np.inf, np.nan], -1, inplace=True)
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)
X_train = np.nan_to_num(X_train)
X_test = np.nan_to_num(X_test)


In [4]:
print(X_train)

[[4.43000000e+02 6.00000000e+00 2.48000000e+02 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [4.43000000e+02 6.00000000e+00 6.00937060e+07 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.12640054e+08 ... 5.09116882e+01
  5.63200630e+07 5.63199910e+07]
 ...
 [5.30000000e+01 1.70000000e+01 2.19000000e+02 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [2.20000000e+01 6.00000000e+00 3.24011000e+05 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [5.30000000e+01 1.70000000e+01 5.66000000e+02 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]]


In [5]:
print(y_train)

['Benign' 'Benign' 'Benign' ... 'Benign' 'SSH-Bruteforce' 'Benign']


In [6]:
print(X_test)

[[2.20000000e+01 6.00000000e+00 6.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [4.43000000e+02 6.00000000e+00 1.18608951e+08 ... 1.25639440e+05
  5.84361170e+07 5.82584360e+07]
 [5.04920000e+04 6.00000000e+00 4.20000000e+01 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 ...
 [5.30000000e+01 1.70000000e+01 6.46000000e+02 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [2.20000000e+01 6.00000000e+00 6.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [3.38900000e+03 6.00000000e+00 1.27270200e+06 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]]


In [7]:
print(y_test)

['SSH-Bruteforce' 'Benign' 'Benign' ... 'Benign' 'SSH-Bruteforce' 'Benign']


## Feature Scaling

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
print(X_train)

[[-3.02983081e-01 -4.72999456e-01 -4.02528653e-03 ... -2.08690334e-03
  -3.20497785e-03 -1.08235861e-01]
 [-3.02983081e-01 -4.72999456e-01  3.85785650e-02 ... -2.08690334e-03
  -3.20497785e-03 -1.08235861e-01]
 [-3.33968727e-01 -1.81741658e+00  7.58318183e-02 ... -2.08678427e-03
   2.98540663e-02  2.74849292e+00]
 ...
 [-3.30261640e-01  1.99176527e+00 -4.02530709e-03 ... -2.08690334e-03
  -3.20497785e-03 -1.08235861e-01]
 [-3.32429936e-01 -4.72999456e-01 -3.79575154e-03 ... -2.08690334e-03
  -3.20497785e-03 -1.08235861e-01]
 [-3.30261640e-01  1.99176527e+00 -4.02506108e-03 ... -2.08690334e-03
  -3.20497785e-03 -1.08235861e-01]]


In [10]:
print(X_test)

[[-3.32429936e-01 -4.72999456e-01 -4.02545809e-03 ... -2.08690334e-03
  -3.20497785e-03 -1.08235861e-01]
 [-3.02983081e-01 -4.72999456e-01  8.00635269e-02 ... -1.79304848e-03
   3.10961587e-02  2.84681701e+00]
 [ 3.19769544e+00 -4.72999456e-01 -4.02543257e-03 ... -2.08690334e-03
  -3.20497785e-03 -1.08235861e-01]
 ...
 [-3.30261640e-01  1.99176527e+00 -4.02500436e-03 ... -2.08690334e-03
  -3.20497785e-03 -1.08235861e-01]
 [-3.32429936e-01 -4.72999456e-01 -4.02545809e-03 ... -2.08690334e-03
  -3.20497785e-03 -1.08235861e-01]
 [-9.69250392e-02 -4.72999456e-01 -3.12316767e-03 ... -2.08690334e-03
  -3.20497785e-03 -1.08235861e-01]]


## Training the SVM model on the Training set

In [11]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

## Predicting a new result

In [12]:
print(classifier.predict(sc.transform([[11,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,2000000,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,40,200,1000000,1000000,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,2,0,26883,0,0,80,0,0,0,0,0,0,0,0]])))

['FTP-BruteForce']


## Predicting the Test set results

In [13]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['SSH-Bruteforce' 'SSH-Bruteforce']
 ['Benign' 'Benign']
 ['Benign' 'Benign']
 ...
 ['Benign' 'Benign']
 ['SSH-Bruteforce' 'SSH-Bruteforce']
 ['Benign' 'Benign']]


## Making the Confusion Matrix

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[133242      2      3]
 [     0  38628      0]
 [     0      8  37377]]


0.9999378763261015

## Visualising the Training set results

## Visualising the Test set results

In [15]:
dataset.columns

Index(['Dst Port', 'Protocol', 'Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts',
       'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Siz